#! /bin/sh

# linux nvidia drivers
xrandr --setprovideroutputsource modesetting NVIDIA-0 &
xrandr --auto &

kitty +kitten themes --reload-in=all Idle Toes
feh --bg-scale ~/bg.jpg &
bash ~/polybar-themes/simple/launch.sh --docky &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

mount /dev/nvme0n1 /mnt/drive
